h5bp/create-html5-boilerplate

- .editorconfig
- package.json
and adds an .editorconfig for consistent code styles.
Partial fix for #3
> Adds homepage, repo and bugs fields to package.json

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SUPPORT.md
- .github/workflows/npmpublish.yml
First commit for this stuff, literally just copied from the main project (which might be fine for now?) Touches on #2 and #1
> stubbing out the .github folder

- README.md
Added a getting started section. More to come
> Adds initial documentation to the readme

- README.md
and I don't think Parcel needs to appear as `code` - so removed that
and remove codefence syntax highlighting language - not needed and removing it makes it slightly easier to read/scan at a glance
> typo fix on README

- .github/workflows/coveralls.yml
Accordiong to:
https://github.com/actions/cache/blob/master/examples.md#node---npm
should speedup our CI tests
> ci: cache node_modules

- README.md
- package.json
> docs: contributing

- cli.js
- package-lock.json
- package.json
This is a proposal. I'd like to hear what you think about it and how should it work.
```bash
$ node index.js ./out/jq
? Remove jQuery? » (y/n)
```
```bash
$ node index.js ./out/s
√ Remove jQuery? ... yes
√ html5-boilerplate@latest copied to D:\projects\create-html5-boilerplate\out\s in 1.59 seconds . Have fun!
```
result (v7.3.0):
```html
<p>Hello world! This is HTML5 Boilerplate.</p>
<script src="js/vendor/modernizr-3.8.0.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/main.js"></script>
```
Also, I'd be happy if you could review regex for removing jQuery: 
```
/(<script>window\.jQuery.*<\/script>|<script src=".*jquery.*<\/script>)/gi
```
[link](https://regex101.com/r/R30Igf/1)
Beside jQuery we can use this for other things like 'Include docs?', 'Install/init …
> feat: remove jquery question

- .github/dependabot.yml
change update frequency to cut down on PR 'noise'.
REF: https://dependabot.com/docs/config-file/#available-schedules
> Change update check in dependabot config to weekly

- package-lock.json
- package.json
> chore: bump version to 0.2

- .github/dependabot.yml
> chore: dependabot versioning strategy

- lib/cli.js
- package-lock.json
- package.json
- tests/test.js
> Update deps & fix test environment for jest

- README.md
https://github.com/h5bp/create-html5-boilerplate/pull/55#issuecomment-699742502
> docs: add Prettier badge to readme

- .github/workflows/codeql-analysis.yml
- lib/cli.js
- package.json
> Release Branch for 0.2.0

- .github/workflows/release.yml
> updates NPM_TOKEN name

- .github/workflows/coveralls.yml
https://nodejs.org/en/about/releases/
* Remove Node 10 and add Node 15 (current)
* use bahmutov/npm-install for npm install caching. Looks much easier than what we do today, and probably will work better.
> ci: use node 15 & use bahmutov/npm-install for caching

- .github/workflows/codeql-analysis.yml
- .github/workflows/coveralls.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
GitHub Actions set to run on the wrong branch
Fixes: #277
Thanks!
> update GitHub Action branch

- .releaserc
> fix(ci): release branch configurations

- package-lock.json
- package.json
> CHORE: manual updates

- package-lock.json
- package.json
This package-lock is just generated. We'll see if it fails, still. 🤔
> updating multiple packages manually

- index.js
- lib/cli.js
- package.json
- tests/test.js
> feat: migrate to ESM

- .github/workflows/codeql-analysis.yml
> CodeQL Analysis GitHub Action fix
